name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * WED'
    # "At 00:00 on Wednesday."

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Fetch OpenAPI Spec and generate code
      run: ./get-spec-and-build.sh

    - name: Run Tests
      run: |
        npm install
        npm run test

    - name: Commit and push if it changed
      run: |-
        ./update_package_json_from_openapi_json.sh

        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Latest version: $(jq -r ".info.version" openapi.json)" || exit 0
        git push